export interface ThemeStyles {
    name: string;
    container: string;
    h2: string;
    h3: string;
    p: string;
    blockquote: string;
    code: string;
    pre: string;
    li: string;
    hr: string;
    table: string;
    th: string;
    td: string;
}

export const THEMES: Record<string, ThemeStyles> = {
    default: {
        name: "默认 (Default)",
        container: "background:#ffffff;color:#333333;padding:20px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;line-height:1.6;",
        h2: "font-size:1.4em;font-weight:bold;margin:24px 0 12px;color:#000000;border-bottom:2px solid #333;padding-bottom:4px;",
        h3: "font-size:1.2em;font-weight:bold;margin:18px 0 8px;color:#000000;",
        p: "margin:10px 0;line-height:1.7;",
        blockquote: "border-left:4px solid #dddddd;margin:16px 0;padding:10px 20px;color:#666666;font-style:italic;background:#f9f9f9;",
        code: "font-family:monospace;background:#f5f5f5;padding:2px 4px;border-radius:3px;color:#c7254e;",
        pre: "background:#f5f5f5;padding:15px;border-radius:5px;overflow-x:auto;margin:16px 0;border:1px solid #eee;",
        li: "margin:4px 0;",
        hr: "border:none;border-top:1px solid #eeeeee;margin:24px 0;",
        table: "border-collapse:collapse;width:100%;margin:16px 0;",
        th: "border:1px solid #ddd;padding:10px;background:#f2f2f2;font-weight:bold;",
        td: "border:1px solid #ddd;padding:10px;",
    },
    modern: {
        name: "现代蓝 (Modern Blue)",
        container: "background:#ffffff;color:#444444;padding:25px;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;",
        h2: "font-size:1.6em;color:#2c3e50;margin:28px 0 14px;border-left:5px solid #3498db;padding-left:15px;",
        h3: "font-size:1.3em;color:#34495e;margin:20px 0 10px;font-weight:600;",
        p: "margin:12px 0;line-height:1.8;text-align:justify;",
        blockquote: "background:#ecf0f1;border-radius:8px;padding:15px 25px;margin:16px 0;color:#7f8c8d;border:none;",
        code: "background:#fef5f5;color:#e74c3c;padding:2px 6px;border-radius:4px;font-weight:500;",
        pre: "background:#2c3e50;color:#ecf0f1;padding:20px;border-radius:10px;margin:16px 0;box-shadow:0 4px 6px rgba(0,0,0,0.1);",
        li: "margin:6px 0;color:#555;",
        hr: "height:2px;background:linear-gradient(to right, #3498db, transparent);border:none;margin:24px 0;",
        table: "border-collapse:collapse;width:100%;margin:16px 0;border-radius:8px;overflow:hidden;box-shadow:0 0 20px rgba(0,0,0,0.05);",
        th: "background:#3498db;color:white;padding:12px;text-align:left;",
        td: "padding:12px;border-bottom:1px solid #eee;",
    },
    elegant: {
        name: "优雅衬线 (Elegant Serif)",
        container: "background:#fffaf5;color:#2d2d2d;padding:30px;font-family:Georgia, serif;line-height:1.8;",
        h2: "font-size:1.8em;text-align:center;color:#8b6b4d;margin:24px 0 12px;font-style:italic;",
        h3: "font-size:1.4em;color:#a67c52;margin:18px 0 9px;border-bottom:1px double #d4b494;padding-bottom:5px;",
        p: "margin:12px 0;letter-spacing:0.05em;",
        blockquote: "margin:16px 0;padding:20px 40px;border:1px solid #e8d0b5;background:#fff;text-align:center;color:#5d4037;",
        code: "font-family:Consolas, Monaco, serif;color:#bf360c;background:#fbe9e7;padding:2px 5px;",
        pre: "background:#fcf8f3;border:1px solid #e0c8b0;padding:20px;line-height:1.5;margin:16px 0;",
        li: "margin:6px 0;list-style-type:circle;",
        hr: "border:none;height:1px;background-color:#d7ccc8;margin:24px 0;",
        table: "width:100%;border-top:2px solid #8b6b4d;border-bottom:2px solid #8b6b4d;margin:16px 0;",
        th: "padding:10px;border-bottom:1px solid #e0c8b0;background:#fdf6ef;",
        td: "padding:10px;border-bottom:1px solid #f3e5f5;",
    },
    minimal: {
        name: "极简黑白 (Minimalist)",
        container: "background:#ffffff;color:#000000;padding:20px;font-family:Arial, sans-serif;max-width:600px;margin:0 auto;",
        h2: "font-size:1.5em;text-transform:uppercase;letter-spacing:2px;border-top:3px solid #000;margin:24px 0 12px;padding-top:10px;",
        h3: "font-size:1.1em;font-weight:900;margin:16px 0 8px;",
        p: "margin:10px 0;line-height:1.5;",
        blockquote: "margin:16px 0;padding-left:20px;border-left:8px solid #000;font-weight:bold;",
        code: "background:#eee;padding:1px 3px;",
        pre: "background:#000;color:#fff;padding:15px;font-size:0.9em;margin:16px 0;",
        li: "margin:4px 0;list-style-type:square;",
        hr: "border:none;border-top:1px solid #000;margin:24px 0;",
        table: "width:100%;margin:16px 0;",
        th: "border-bottom:2px solid #000;padding:8px;text-align:left;",
        td: "border-bottom:1px solid #eee;padding:8px;",
    },
    night: {
        name: "深色极客 (Night Mode)",
        container: "background:#1e1e1e;color:#d4d4d4;padding:20px;font-family:'Courier New', Courier, monospace;",
        h2: "color:#4ec9b0;font-size:1.4em;margin:18px 0 9px;border-bottom:1px solid #333;padding-bottom:5px;",
        h3: "color:#ce9178;font-size:1.2em;margin:14px 0 7px;",
        p: "margin:10px 0;line-height:1.6;",
        blockquote: "background:#252526;border-left:5px solid #007acc;padding:15px;margin:16px 0;",
        code: "color:#d7ba7d;background:#2d2d2d;padding:2px 4px;",
        pre: "background:#000000;border:1px solid #444;padding:15px;border-radius:4px;margin:16px 0;",
        li: "margin:4px 0;color:#9cdcfe;",
        hr: "border:none;border-top:1px solid #444;margin:24px 0;",
        table: "width:100%;border:1px solid #333;margin:16px 0;",
        th: "background:#333;color:#fff;padding:10px;",
        td: "border:1px solid #333;padding:10px;",
    },
    academic: {
        name: "学术严谨 (Academic)",
        container: "background:#ffffff;color:#111;padding:30px;font-family:'Times New Roman', Times, serif;line-height:1.5;text-align:justify;",
        h2: "text-align:center;font-size:1.3em;font-weight:bold;margin:20px 0 10px;text-transform:uppercase;",
        h3: "font-size:1.1em;font-weight:bold;margin:14px 0 7px;font-style:italic;",
        p: "text-indent:2em;margin:8px 0;",
        blockquote: "margin:16px 24px;font-size:0.9em;line-height:1.4;color:#444;",
        code: "font-family:monospace;font-size:0.9em;border:1px solid #ccc;padding:0 2px;",
        pre: "border:1px solid #333;padding:10px;margin:16px 0;font-size:0.85em;background:#fff;",
        li: "margin:4px 0;margin-left:2em;",
        hr: "border:none;border-top:0.5px solid #000;margin:24px 0;",
        table: "width:100%;border-top:1.5px solid #000;border-bottom:1.5px solid #000;margin:16px 0;font-size:0.9em;",
        th: "border-bottom:1px solid #000;padding:5px;font-weight:bold;",
        td: "padding:5px;",
    },
    nature: {
        name: "清新自然 (Nature Green)",
        container: "background:#f1f8e9;color:#2e7d32;padding:25px;font-family:'Segoe UI', Tahoma, sans-serif;",
        h2: "font-size:1.5em;background:#81c784;color:white;padding:10px 20px;border-radius:25px;display:inline-block;margin:18px 0 9px;",
        h3: "font-size:1.2 em;color:#4caf50;margin:14px 0 7px;border-left:4px solid #81c784;padding-left:12px;",
        p: "margin:10px 0;line-height:1.7;color:#33691e;",
        blockquote: "background:#e8f5e9;border-radius:15px;padding:20px;border:1px solid #c8e6c9;margin:16px 0;color:#1b5e20;",
        code: "background:#c8e6c9;color:#2e7d32;padding:2px 5px;border-radius:5px;",
        pre: "background:#33691e;color:#f1f8e9;padding:15px;border-radius:12px;margin:16px 0;",
        li: "margin:4px 0;list-style-type:disc;",
        hr: "height:4px;background:#c8e6c9;border:none;border-radius:2px;margin:24px 0;",
        table: "width:100%;background:white;border-radius:10px;overflow:hidden;margin:16px 0;",
        th: "background:#a5d6a7;padding:10px;color:#1b5e20;",
        td: "padding:10px;border-bottom:1px solid #f1f8e9;",
    },
    kawaii: {
        name: "可爱粉嫩 (Kawaii Pink)",
        container: "background:#fff5f7;color:#d81b60;padding:20px;font-family:'Comic Sans MS', cursive, sans-serif;",
        h2: "font-size:1.6em;text-align:center;color:#ff80ab;margin:18px 0 9px;text-shadow:2px 2px #f8bbd0;",
        h3: "font-size:1.3em;color:#f06292;margin:14px 0 7px;display:flex;align-items:center;&:before{content:'🌸';margin-right:8px;}",
        p: "margin:10px 0;line-height:1.8;letter-spacing:0.02em;",
        blockquote: "background:#fce4ec;border:2px dashed #f48fb1;border-radius:20px;padding:15px;margin:16px 0;text-align:center;",
        code: "background:#f8bbd0;color:#ad1457;padding:2px 8px;border-radius:10px;",
        pre: "background:#fff;border:3px solid #f8bbd0;padding:15px;border-radius:20px;margin:16px 0;",
        li: "margin:5px 0;list-style-type:'💖 ';",
        hr: "background-image:linear-gradient(to right, transparent, #ff80ab, transparent);height:3px;border:none;margin:24px 0;",
        table: "width:100%;border:2px solid #f8bbd0;border-radius:15px;margin:16px 0;background:white;",
        th: "background:#fce4ec;padding:10px;",
        td: "padding:10px;border-top:1px dashed #f8bbd0;",
    },
    retro: {
        name: "复古报纸 (Retro News)",
        container: "background:#e6dcc5;color:#333;padding:30px;font-family:'Courier New', monospace;box-shadow:inset 0 0 100px rgba(0,0,0,0.1);",
        h2: "font-size:2em;text-align:center;font-weight:900;border-top:4px solid #333;border-bottom:4px solid #333;padding:10px 0;margin:24px 0 12px;",
        h3: "font-size:1.5em;font-weight:700;margin:16px 0 8px;text-decoration:underline;",
        p: "margin:8px 0;line-height:1.4;column-count:1;",
        blockquote: "border:1px solid #333;padding:15px;margin:16px 0;background:rgba(255,255,255,0.3);",
        code: "background:#ccc;padding:0 4px;",
        pre: "background:#333;color:#eee;padding:15px;margin:16px 0;white-space:pre-wrap;",
        li: "margin:4px 0;text-transform:uppercase;",
        hr: "height:10px;border-top:2px solid #333;border-bottom:4px solid #333;margin:24px 0;",
        table: "width:100%;border:2px solid #333;margin:16px 0;",
        th: "background:#333;color:#eee;padding:10px;",
        td: "border:1px solid #333;padding:8px;",
    },
    tech: {
        name: "科技橙 (Tech Orange)",
        container: "background:#0a0a0a;color:#eee;padding:25px;font-family:Inter, system-ui, sans-serif;",
        h2: "font-size:1.8em;color:#ff6b00;margin:28px 0 14px;font-weight:800;letter-spacing:-1px;",
        h3: "font-size:1.2em;color:#ffa500;margin:20px 0 10px;text-transform:uppercase;letter-spacing:1px;",
        p: "margin:14px 0;line-height:1.8;color:#ccc;",
        blockquote: "background:rgba(255,107,0,0.1);border-left:4px solid #ff6b00;padding:20px;margin:16px 0;border-radius:0 8px 8px 0;",
        code: "background:#333;color:#ff6b00;padding:2px 6px;border-radius:4px;",
        pre: "background:#111;border:1px solid #333;padding:20px;border-radius:8px;box-shadow:0 10px 30px rgba(0,0,0,0.5);margin:16px 0;",
        li: "margin:4px 0;color:#bbb;",
        hr: "height:1px;background:#333;border:none;margin:24px 0;",
        table: "width:100%;border-collapse:separate;border-spacing:0 8px;margin:16px 0;",
        th: "color:#ff6b00;text-align:left;padding:12px;border-bottom:2px solid #ff6b00;",
        td: "background:#1a1a1a;padding:12px;border-top:1px solid #222;",
    },
};
